// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7gZ2ygFTxYPo39sSh4R993whjRcgVgc4',
    appId: '1:1097618524829:web:5f222d750c1ace7add6274',
    messagingSenderId: '1097618524829',
    projectId: 'tourguide-bb7a2',
    authDomain: 'tourguide-bb7a2.firebaseapp.com',
    databaseURL: 'https://tourguide-bb7a2-default-rtdb.firebaseio.com',
    storageBucket: 'tourguide-bb7a2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx8f7jPRMd3jmUttP2FZOT7D4QySXde3I',
    appId: '1:1097618524829:ios:6c2beda771c83ea0dd6274',
    messagingSenderId: '1097618524829',
    projectId: 'tourguide-bb7a2',
    databaseURL: 'https://tourguide-bb7a2-default-rtdb.firebaseio.com',
    storageBucket: 'tourguide-bb7a2.appspot.com',
    iosBundleId: 'com.example.mobiletourguide.RunnerTests',
  );
}
